# pcgr_predispose configuration options (TOML).

[cancer_predisposition_genes]
ABRAXAS1 = true
ACD = true
AIP = true
AKT1 = true
ALK = true
APC = true
APOBEC3B = false
AR = false
ATM = true
ATR = false
AXIN2 = true
BAP1 = true
BARD1 = true
BLM = true
BMPR1A = true
BRCA1 = true
BRCA2 = true
BRIP1 = true
BUB1B = true
CASR = true
CDC73 = true
CDH1 = true
CDH10 = false
CDK4 = true
CDKN1B = true
CDKN1C = true
CDKN2A = true
CEBPA = true
CEP57 = true
CHEK2 = true
CTNNA1 = true
CTNNB1 = true
CTRC = true
CXCR4 = false
CYLD = true
DDB2 = true
DICER1 = true
DIRAS3 = true
DIS3L2 = true
DTX3L = true
EGFR = true
ERBB4 = false
ERCC1 = true
ERCC2 = true
ERCC3 = true
ERCC4 = true
ERCC5 = true
ETV6 = true
EXT1 = true
EXT2 = true
EZH2 = true
FANCA = true
FANCB = true
FANCC = true
FANCD2 = true
FANCE = true
FANCF = true
FANCG = true
FANCI = true
FANCL = true
FANCM = true
FAT1 = false
FEN1 = false
FH = true
FLCN = true
GALNT12 = true
GATA2 = true
GPC3 = true
GREM1 = true
HABP2 = true
HNF1A = true
HNF1B = true
HOXB13 = true
HRAS = true
KDR = false
KIF1B = true
KIT = true
LMO1 = false
LZTR1 = true
MAX = true
MEN1 = true
MET = true
MITF = true
MLH1 = true
MPL = false
MRE11 = true
MSH2 = true
MSH3 = true
MSH6 = true
MUTYH = true
NBN = true
NF1 = true
NF2 = true
NSD1 = true
NTHL1 = true
OGG1 = true
PALB2 = true
PAX5 = true
PDGFRA = true
PHOX2B = true
PIK3CA = true
PINK1 = true
PMS1 = true
PMS2 = true
POLD1 = true
POLE = true
POLQ = false
POT1 = true
PPM1D = true
PRF1 = true
PRKAR1A = true
PRSS1 = true
PTCH1 = true
PTEN = true
PTPN11 = true
PTPN13 = false
RAD50 = true
RAD51 = true
RAD51B = true
RAD51C = true
RAD51D = true
RB1 = true
RCC2 = true
RECQL4 = true
RET = true
RFWD3 = false
RHBDF2 = true
RING1 = true
RINT1 = true
RUNX1 = true
SBDS = true
SCG5 = true
SDHA = true
SDHAF2 = true
SDHB = true
SDHC = true
SDHD = true
SETBP1 = false
SLX4 = true
SMAD4 = true
SMARCA4 = true
SMARCB1 = true
SMARCE1 = true
SPINK1 = true
SPOP = false
SPRED1 = true
STAT3 = false
STK11 = true
SUFU = true
TERF2IP = true
TERT = true
TGFBR2 = false
TMEM127 = true
TP53 = true
TP63 = false
TSC1 = true
TSC2 = true
TSHR = false
VHL = true
WAS = false
WRN = true
WT1 = true
XPA = true
XPC = true
XRCC2 = true

[tumor_type]
## Currently not used
Adrenal_Gland_Cancer_NOS = false
Ampullary_Carcinoma_NOS = false
Biliary_Tract_Cancer_NOS = false
Bladder_Urinary_Tract_Cancer_NOS = false
Blood_Cancer_NOS = false
Bone_Cancer_NOS = false
Breast_Cancer_NOS = true
CNS_Brain_Cancer_NOS = false
Colorectal_Cancer_NOS = false
Cervical_Cancer_NOS = false
DNA_Repair_Deficiency_Disorders = false
Esophageal_Stomach_Cancer_NOS = false
Head_And_Neck_Cancer_NOS = false
Hereditary_Cancer_NOS = false
Kidney_Cancer_NOS = false
Leukemia_NOS = false
Liver_Cancer_NOS = false
Lung_Cancer_NOS = false
Lymphoma_Hodgkin_NOS = false
Lymphoma_Non_Hodgkin_NOS = false
Mesothelioma = false
Multiple_Myeloma = false
Ovarian_Fallopian_Tube_Cancer_NOS = false
Pancreatic_Cancer_NOS = false
Penile_Cancer_NOS = false
Peripheral_Nervous_System_Cancer_NOS = false
Peritoneal_Cancer_NOS = false
Pleural_Cancer_NOS = false
Prostate_Cancer_NOS = false
Skin_Cancer_NOS = false
Soft_Tissue_Cancer_NOS = false
Stomach_Cancer_NOS = false
Testicular_Cancer_NOS = false
Thymic_Cancer_NOS = false
Thyroid_Cancer_NOS = false
Uterine_Cancer_NOS = false
Vulvar_Vaginal_Cancer_NOS = false

[visual]
# Choose visual theme of report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = "default"

[other]
vcf_validation = true
n_vcfanno_proc = 4
n_vep_forks = 4
vep_skip_intergenic = false
